on:
  push:
    branches:
      - master
  pull_request:

name: lint

jobs:
  fmt:
    name: rust fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set profile
        run: rustup set profile minimal

      - name: Install nightly toolchain
        run: rustup toolchain install nightly

      - name: Install stable toolchain
        run: rustup toolchain install stable

      - name: Add rustfmt
        run: rustup component add rustfmt --toolchain nightly

      - name: Add clippy
        run: rustup component add clippy --toolchain stable

      - name: Update toolchain
        run: rustup update

      - name: Check fmt
        run: cargo +nightly fmt --all -- --check

      - name: Clippy (main codebase with all features)
        run: cargo +stable clippy --all-features --lib --bins --tests -- -D warnings

      - name: Clippy (examples with default features only)
        run: cargo +stable clippy --examples -- -D warnings

      # - name: cargo install cargo-hack
      #   uses: taiki-e/install-action@cargo-hack

      # - name: cargo hack
      #   run: cargo hack --feature-powerset check

      - name: Check docs
        env:
          RUSTDOCFLAGS: "-D warnings"
        run: cargo +nightly doc --all-features --document-private-items --no-deps